name: 'get-release-branch-version'
description: 'Gets the version number of a release branch such as release/1.2'
author: 'insidersoftware'
outputs:
  major:
    description: 'The major version number such as 1 in release/1.2.3'
  minor:
    description: 'The minor version number such as 2 in release/1.2.3'
  manifestSafeVersionString:
    description: 'A version string that is save to use in Dnn manifests'
runs:
  using: 'node12'
  main: './dist/index.js'
